# Generated by Django 3.2.8 on 2022-03-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220225_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bezel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fullyStickered',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='powerReserve',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='waterResistant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
