# Generated by Django 3.2.8 on 2022-08-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_order_orderitem_review_shippingaddress_subscriberlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arrangementNumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
